# Generated by Django 4.0.5 on 2022-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_trendinggame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rank',
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
