# Generated by Django 4.0.5 on 2022-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_game_rank_game_max_players_game_min_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_ag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
