# Generated by Django 4.0.5 on 2022-06-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_game_min_ag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='min_ag',
            new_name='min_age',
        ),
    ]
