# Generated by Django 4.0.5 on 2022-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_min_ag_game_min_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='playtime',
        ),
        migrations.AddField(
            model_name='game',
            name='min_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
