# Generated by Django 4.0.5 on 2022-06-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_game_playtime_game_min_playtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
