# Generated by Django 4.0.5 on 2022-06-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_game_slug_trendinggame_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
