# Generated by Django 4.0.5 on 2022-06-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_name',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='main_app.game')),
            ],
        ),
    ]
