# Generated by Django 4.0.5 on 2022-06-10 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_remove_collection_collection_name_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['bgg_id']},
        ),
        migrations.AlterModelOptions(
            name='trendinggame',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
