# Generated by Django 4.0.5 on 2022-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_game_options_alter_trendinggame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
